### ISSUE TITLE
Adding Newer Epochs

### ISSUE THREAD

**Issue by dete** [psiemens/stakeout#3]
Love the tool! It's a shame it requires you to manually update epochs.csv. Can you share how that is generated so we can update it ourselves when necessary?

**Comment by psiemens** [comment]
Thanks! Sadly epochs.csv wasn't generated. I manually scraped the epoch transaction IDs from the [service account repository](https://github.com/onflow/service-account/tree/main/transactions/pay-rewards/) because we couldn't easily query a list of historical transactions at the time.

However, I just updated the tool to use the [Find Labs Historical API](https://github.com/onflow/service-account/tree/main/transactions/pay-rewards/) (thank you @bjartek + team!), so it should stay up to date without any manual updates going forward.

Stakeout was always a bit of a stopgap solution in lieu of more user-friendly alternatives. I'll likely deprecate it once something better exists -- its new status as a Find Labs API wrapper brings it one step closer to that. 😄
